language: python
matrix:
    include:
        -   env: TOXENV=py37
            dist: xenial
            python: 3.7
install: pip install tox
script: tox
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
